### ISSUE TITLE
Viewing transcriptions and media player

### ISSUE THREAD

**Issue by johndmccrory** [ivyrze/omeka-s-module-transcript#5]
Hi ivyrze,

Many thanks for making this (and other Omeka S modules) available, along with the Multilingual theme.

I'd love to explore this module with the Multilingual theme, in particular for audio and video files with WebVTT captions. Forgive me for being slow- I'm probably missing something obvious!- but I can't view either the media player or transcriptions with the module installed (from source). A couple of questions:

1. Is the updated media player/transcript feature only available in the Item Show page, or is it a block that can be added to a page?
2. My audio and video files with WebVTT captions are added as HTML media in Omeka S: is there a better way of associating audiovisual media with WebVTT captions for this module?

All the best,
John

**Comment by ivyrze** [comment]
Glad to hear the modules are getting some use! Here are the answers to your questions:

1. No, in addition to it being available on the item show and media show pages, you can use the Omeka’s “media embed” page block to show a particular item’s player on a general page.
2. When media is uploaded to an item, you must use the WebVTT ingester listed in the sidebar. It’ll prompt you to select the audio-video file and the VTT file at that time.

As is touched on in the README file, I would discourage you from using the WebVTT section of this module with large videos. I’ve found [this article](https://wp101.com/10-reasons-why-you-should-never-host-your-own-videos/) to talk generally about why. The biggest issue is that it will be painfully slow to watch, especially if your users are on mobile data. Audio can be susceptible to these issues as well, but since the files tend to be smaller it’s not as much of a generally stated concern. If any of your files are bigger than a handful MBs, consider using the Vimeo option.

**Comment by johndmccrory** [comment]
Excellent! Many thanks for responding, and so quickly too- it now works perfectly.

Your advice about self-hosting videos is duly noted, and it looks a great option for smaller audio files.

Cheers,
John
